"""Typing stubs for the `bytetok.bpe` public wrapper module.

This file intentionally exposes Rust-backed symbols via the public path
`bytetok.bpe` so tooling prefers:

`from bytetok.bpe import RustBPETrainer`

over the internal extension path:

`from bytetok._bpe_rs import RustBPETrainer`
"""

from __future__ import annotations

class RustBPETrainer:
    def __init__(self, tokens: list[int], next_token_id: int) -> None: ...
    def train(self, num_merges: int) -> None: ...
    def merge_step(self) -> bool: ...
    def get_tokens(self) -> list[int]: ...
    def get_merge_history(self) -> list[tuple[tuple[int, int], int]]: ...
    def print_state(self) -> None: ...

class RustBPEEncoder:
    def __init__(self, merge_history: list[tuple[tuple[int, int], int]]) -> None: ...
    def encode(self, tokens: list[int]) -> list[int]: ...
    def can_merge(self, left: int, right: int) -> bool: ...
    def num_merges(self) -> int: ...

__all__ = ["RustBPETrainer", "RustBPEEncoder"]
